package com.ab.hicareservices.utils
data class UserData(
    var User_Id: Int = 0,
    var Address_Id: Int = 0,
    var WebId: String = "",
    var WebCustId: String = "",
    var Fname: String = "",
    var LastName: String = "",
    var Email: String = "",
    var MobileNo: String = "",
    var CommunicationMobileNo: String = "",
    var AltMobileNo: String = "",
    var Pincode: String = "",
    var Remarks: String = "",
    var BHK: String = "",
    var ServiceArea: String = "",
    var OrderCreatedDatetime: String = "",
    var LeadSource: String = "",
    var CampaignCode: String = "",
    var PaymentStatus: String = "",
    var PGResponse: String = "",
    var MRP: String = "",
    var DiscountValue: String = "",
    var DiscountPercent: String = "",
    var OrderValue: String = "",
    var VoucherCode: String = "",
    var OnlinePaidAmount: String = "",
    var PaybackPaidAmount: String = "",
    var AppointmentStartDateTime: String = "",
    var AppointmentEndDateTime: String = "",
    var FlatNo: String = "",
    var BuildingName: String = "",
    var Locality: String = "",
    var Landmark: String = "",
    var Street: String = "",
    var City: String = "",
    var State: String = "",
    var Lat: String = "",
    var Long: String = "",
    var ServiceCode: String = "",
    var Param1: String = "",
    var Param2: String = "",
    var Param3: String = "",
    var Source: String = "",
    var SubSource: String = "",
    var UtmSource: String = "",
    var UtmSubsource: String = "",
    var OrderCreatedFrom: String = "",
    var Subscription: String = "",
    var ServiceType: String = "",
    var Customer_Type: String = "",
    var Created_On: String = "",
    var Hygiene_Point_Percentage: String = "",
    var Redeem_Hygine_Points: String = "",
    var Is_Subscription_Order: Boolean = false,
    var Subscription_Id: String = "",
    var Subscription_Plan_Id: String = "",
    var OrderPayments: List<OrderPayment> = listOf(),
    var Campaign_Url: String = ""
)

data class OrderPayment(
    var PaymentMode: String = "",
    var PaymentMethod: String = "",
    var Amount: String = "",
    var TransactionId: String = "",
    var Type: String = ""
)
